#!/bin/bash
# Quick usage examples for object_detector.py

echo "=========================================="
echo "  Object Detector - Quick Reference"
echo "=========================================="
echo ""
echo "Pipeline Modes:"
echo "  --mode detect                # Detection only (default)"
echo "  --mode detect-display        # Detection + display"
echo "  --mode display               # Display only"
echo "  --mode record                # Record video"
echo "  --mode record-display        # Record + display"
echo "  --mode record-detect-display # All features"
echo ""
echo "Basic Examples:"
echo "  ./run_detector.sh                                    # Detection only"
echo "  ./run_detector.sh --mode detect-display              # Detect + show"
echo "  ./run_detector.sh --mode display                     # View only"
echo "  ./run_detector.sh --mode record                      # Record video"
echo ""
echo "With Models:"
echo "  ./run_detector.sh --custom-model my.onnx             # Custom ONNX"
echo "  ./run_detector.sh --compare --mode detect-display    # Compare models"
echo ""
echo "Recording:"
echo "  ./run_detector.sh --mode record-display              # Record + view"
echo "  ./run_detector.sh --mode record-detect-display \\     # Full featured"
echo "                    --model onnx --verbose"
echo ""
echo "Advanced:"
echo "  ./run_detector.sh --mode record-detect-display \\     # Everything!"
echo "                    --compare --device 2 --verbose"
echo ""
echo "=========================================="

